name: {{#snakeCase}}{{project_name}}{{/snakeCase}}_library
description: {{{project_name}}} library
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  formz: ^0.4.1
  
dev_dependencies:
  test: ^1.16.4
  very_good_analysis: ^2.4.0
