name: authentication_repository
description: A Dart Repository which manages the authentication domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  codebuds_client:
    path: ../{{{api_client_name}}}_client

dev_dependencies:
  test: ^1.16.4
  very_good_analysis: ^3.1.0
