name: {{#snakeCase}}{{api_client_name}}{{/snakeCase}}_client
description: {{{api_client_name}}} api client
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.0
  flutter_secure_storage: ^4.2.0
  fresh: ^0.4.0
  fresh_dio: ^0.3.1
  json_annotation: ^4.4.0
  json_serializable: ^6.1.3


dev_dependencies:
  build_runner: ^2.1.2
  test: ^1.16.4
  very_good_analysis: ^2.4.0
